---
logging:
  level:
    in.shabhushan: 'DEBUG'
    org.springframework: 'WARN'

server:
  port: ${random.int(15000,15100)}

info:
  version: 1.0
  name:  Ticket Booking

spring:
  datasource:
    url: jdbc:mysql://<host>/ticket_booking?enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: <user>
    password: <password>

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  metrics:
    export:
      influx:
        enabled: true
        db: ticket_booking
        uri: http://<host>:<port>
        user-name: <user>
        password: <password>
        step: 1m
  endpoints:
    web:
      expose: "*"

com:
  ticketbooking:
    shows:
      cache:
        size: 10
        durationSeconds: 30