INSERT INTO users (create_time, update_time, username, password) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "shashi", "superSecret");
INSERT INTO customers (create_time, update_time, city, email, first_name, last_name, phone_number, state, user_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), 1, "email@domain.com", "Shashi", "Bhushan", "12345", 1, 1);

INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Terence Fisher", 87, 0, "The Hound of Baskervilles", "Anthony Hinds", STR_TO_DATE('4,5,1959','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "The Wachowskis", 136, 0, "The Matrix", "Joel Silver", STR_TO_DATE('24,3,1999','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "The Wachowskis", 138, 0, "The Matrix Reloaded", "Joel Silver", STR_TO_DATE('15,5,2003','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "The Wachowskis", 129, 0, "The Matrix Revolutions", "Joel Silver", STR_TO_DATE('5,11,2003','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Client Eastwood", 133, 0, "Invictus", "Client Eastwood", STR_TO_DATE('11,12,2009','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Tom Shadyac", 101, 0, "Bruce Almighty", "Tom Shadyac", STR_TO_DATE('14,5,2003','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Peter Jackson", 178, 0, "Lord of the Rings (LOTR) The Fellowship of the Ring", "Peter Jackson", STR_TO_DATE('10,12,2001','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Peter Jackson", 179, 0, "Lord of the Rings (LOTR) The Two Towers", "Peter Jackson", STR_TO_DATE('5,12,2002','%d,%m,%Y'));
INSERT INTO movies (create_time, update_time, director, duration_minutes, language, name, producer, release_date) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Peter Jackson", 201, 0, "Lord of the Rings (LOTR) The Return of the King", "Peter Jackson", STR_TO_DATE('1,12,2003','%d,%m,%Y'));

INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "PVR");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Harihar Talkies");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Inox");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "PVR");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Carnival Cinema");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Big Cinema");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Harihar Talkies");
INSERT INTO cinemas (create_time, update_time, name) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), "Harihar Talkies");

INSERT INTO addresses (street, city, state, cinema_id) values ("101 new Street", "BANGALORE", "KARNATAKA", 1);
INSERT INTO addresses (street, city, state, cinema_id) values ("purane mandir ke saamne", "BANGALORE", "KARNATAKA", 2);
INSERT INTO addresses (street, city, state, cinema_id) values ("102 the other Street", "BANGALORE", "KARNATAKA", 3);
INSERT INTO addresses (street, city, state, cinema_id) values ("420 the fabulous Street", "BANGALORE", "KARNATAKA", 4);
INSERT INTO addresses (street, city, state, cinema_id) values ("Adjacent to Inox Cinema", "BANGALORE", "KARNATAKA", 5);
INSERT INTO addresses (street, city, state, cinema_id) values ("just before Small Cinema", "BANGALORE", "KARNATAKA", 6);
INSERT INTO addresses (street, city, state, cinema_id) values ("103 bloody old Street", "PUNE", "MAHARASTRA", 7);
INSERT INTO addresses (street, city, state, cinema_id) values ( "410 back passage road", "MUMBAI", "MAHARASTRA", 8);

INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 1, 4, 1);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 2, 4, 1);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 3, 4, 1);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 4, 4, 1);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 1, 4, 2);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 2, 4, 2);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 3, 4, 2);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 4, 4, 2);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 1, 4, 3);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 2, 4, 3);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 3, 4, 3);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 4, 4, 3);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 1, 4, 4);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 2, 4, 4);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 3, 4, 4);
INSERT INTO halls (create_time, update_time, hall_number, seat_count, cinema_id) values(UTC_TIMESTAMP(), UTC_TIMESTAMP(), 4, 4, 4);

INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('09,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), 1, (SELECT id FROM movies WHERE name = "The Matrix"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), 1, (SELECT id FROM movies WHERE name = "The Matrix"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), 1, (SELECT id FROM movies WHERE name = "The Matrix"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('21,0,1,1,2022','%H,%i,%d,%m,%Y'), 1, (SELECT id FROM movies WHERE name = "The Matrix"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('09,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), 2, (SELECT id FROM movies WHERE name = "Bruce Almighty"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), 2, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Fellowship of the Ring"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), 2, (SELECT id FROM movies WHERE name = "Bruce Almighty"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('21,0,1,1,2022','%H,%i,%d,%m,%Y'), 2, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Fellowship of the Ring"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), 3, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Two Towers"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('21,0,1,1,2022','%H,%i,%d,%m,%Y'), 3, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Two Towers"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('09,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), 3, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Return of the King"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), 3, (SELECT id FROM movies WHERE name = "Lord of the Rings (LOTR) The Return of the King"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), 4, (SELECT id FROM movies WHERE name = "Bruce Almighty"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('18,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('21,0,1,1,2022','%H,%i,%d,%m,%Y'), 4, (SELECT id FROM movies WHERE name = "Bruce Almighty"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('09,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), 4, (SELECT id FROM movies WHERE name = "Bruce Almighty"));
INSERT INTO shows (create_time, update_time, start_time, end_time, hall_id, movie_id) values (UTC_TIMESTAMP(), UTC_TIMESTAMP(), STR_TO_DATE('12,0,1,1,2022','%H,%i,%d,%m,%Y'), STR_TO_DATE('15,0,1,1,2022','%H,%i,%d,%m,%Y'), 4, (SELECT id FROM movies WHERE name = "Bruce Almighty"));